/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.34
 * Generated at: 2020-05-14 09:26:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.SQLException;
import java.io.IOException;

public final class mylocations_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.sql.SQLException");
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("java.sql.Statement");
    _jspx_imports_classes.add("java.io.IOException");
    _jspx_imports_classes.add("java.sql.DriverManager");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<title>My Locations</title>\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css\">\r\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js\"></script>\r\n");
      out.write("  <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <style type=\"text/css\">\r\n");
      out.write("  \t.mybtn{\r\n");
      out.write("  \t\ttransition: 0.3s ease;\r\n");
      out.write("\r\n");
      out.write("  \t}\r\n");
      out.write("  \t.mybtn:hover{\r\n");
      out.write("  \t\tbackground-color: white;\r\n");
      out.write("  \t\tcolor: black;\r\n");
      out.write("  \t}\r\n");
      out.write("  \t.mybtn2{\r\n");
      out.write("  \t\ttransition: 0.3s ease;\r\n");
      out.write("  \t\tbackground-color: #D6A511;\r\n");
      out.write("\r\n");
      out.write("  \t}\r\n");
      out.write("  \t.mybtn2:hover{\r\n");
      out.write("  \t\tbackground-color: white;\r\n");
      out.write("  \t\tcolor: black;\r\n");
      out.write("  \t}\r\n");
      out.write("  \t\r\n");
      out.write("  </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
          HttpSession mysession=request.getSession(); 
if(mysession.getAttribute("aadhar")==null){
	response.sendRedirect("login.jsp");
}


      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"myModal\" class=\"modal fade\">\r\n");
      out.write("    <div class=\"modal-dialog\">\r\n");
      out.write("        <div class=\"modal-content\">\r\n");
      out.write("            <div class=\"modal-header\">\r\n");
      out.write("                <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-hidden=\"true\">&times;</button>\r\n");
      out.write("                <h4 class=\"modal-title\">Enter Your Location</h4>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"modal-body\">\r\n");
      out.write("\t\t\r\n");
      out.write("                <form method=\"get\" action=\"AddL\">\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <input type=\"text\" class=\"form-control\" name=\"location\" id=\"myPopupInput\" placeholder=\"Your Current Location\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <input type=\"submit\" name=\"submit\" class=\"btn btn-primary\" id=\"modal-closed\"  value=\"Submit\">\r\n");
      out.write("                </form>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div id=\"myModal4\" class=\"modal fade\">\r\n");
      out.write("    <div class=\"modal-dialog\">\r\n");
      out.write("        <div class=\"modal-content\">\r\n");
      out.write("            <div class=\"modal-header\">\r\n");
      out.write("                <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-hidden=\"true\">&times;</button>\r\n");
      out.write("                <h4 class=\"modal-title\">Enter Location To be removed</h4>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"modal-body\">\r\n");
      out.write("\t\t\r\n");
      out.write("                <form method=\"get\" action=\"RemoveL\">\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <input type=\"text\" class=\"form-control\" name=\"location\" id=\"myPopupInput\" placeholder=\"Your Current Location\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <input type=\"submit\" name=\"submit\" class=\"btn btn-primary\" id=\"modal-closed\"  value=\"Submit\">\r\n");
      out.write("                </form>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("\t\r\n");
      out.write("\t<button class=\"btn btn-info mybtn2\" style=\"float:right; margin: 5px;\" onclick=\"window.location.href='home.jsp'\">RETURN TO HOME</button>\r\n");
      out.write("</div>\r\n");
      out.write("\t<div class=\"container\" style=\"background-color:#f3f3f3;\">\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"col-md-3\">\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<img src=\"map.png\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<h2 align=\"center\">MY LOCATIONS</h2>\r\n");
      out.write("\t\t\t<p align=\"center\">SAFE ZONES</p>\r\n");
      out.write("\t\t\t<div align=\"center\">\r\n");
      out.write("\t\t\t<button type=\"button\" id=\"open-modal2\" class=\"btn btn-info mybtn\" float=\"center\" data-toggle=\"modal\" data-target=\"#myModal\" \r\n");
      out.write("style=\"margin-right: 5px;\">Add Location</button>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<button type=\"button\" id=\"open-modal4\" class=\"btn btn-info mybtn\" float=\"center\" data-toggle=\"modal\" data-target=\"#myModal4\" \r\n");
      out.write("style=\"margin-right: 5px;\">Remove a Location</button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"col-md-3\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<table class=\"table\">\r\n");
      out.write("\t\t    <thead>\r\n");
      out.write("\t\t      <tr>\r\n");
      out.write("\t\t        <th>S.no</th>\r\n");
      out.write("\t\t        <th>Location</th>\r\n");
      out.write("\t\t      </tr>\r\n");
      out.write("\t\t    </thead>\r\n");
      out.write("\t\t    <tbody>\r\n");
      out.write("\t\t     \r\n");
      out.write("\t\r\n");
      out.write("\t");

	Connection conn = null;
    try {
    	String aadhar = (String)mysession.getAttribute("aadhar");

    	Class.forName("com.mysql.jdbc.Driver");
        String url = "jdbc:mysql://localhost:3306/javadbms?verifyServerCertificate=false&useSSL=true";
        String user = "root";
        String dbpassword = "wiseone";
    	
        
        conn = DriverManager.getConnection(url, user, dbpassword);
        String sql="select * from locations where aadhar='"+aadhar+"';";
        Statement st = conn.createStatement(); 
        ResultSet m = st.executeQuery(sql); 
        int i=1;
        while(m.next()) {
        	
      out.write("\r\n");
      out.write("        \t<tr>\r\n");
      out.write("        \t<td>");
      out.print(i );
      out.write("</td>\r\n");
      out.write("        \t<td>");
      out.print(m.getString(2) );
      out.write("</td>\r\n");
      out.write("        \t<tr>\r\n");
      out.write("        \t");

        	i=i+1;
        	}
        	
        
        

    } catch(SQLException e) {
       System.out.println(e.getMessage());
    } catch (ClassNotFoundException e) {
		// TODO Auto-generated catch block
    	e.printStackTrace();
    }
	
      out.write("\r\n");
      out.write("\t      \r\n");
      out.write("\t\t    </tbody>\r\n");
      out.write("        </table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
